# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "Kubenews-devops123"
          - name: POSTGRES_USER
            value: "kubenews-user"
          - name: POSTGRES_DB
            value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-kubenews
spec:
  replicas: 20
  selector:
    matchLabels:
      app: devops-kubenews
  template:
    metadata:
      labels:
        app: devops-kubenews
    spec:
      containers:
      - name: devops-kubenews
        image: vesteves33/kube-news:v2
        env:
        - name: DB_DATABASE 
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews-user"
        - name: DB_PASSWORD
          value: "Kubenews-devops123"
        - name: DB_HOST
          value: "postgre"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-kubenews
spec:
  selector:
    app: devops-kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer

